name: midjourney_api_dart
description: Unofficial dart client that provides a simple interface to interact with Midjourney API.
version: 1.0.4

environment:
  sdk: ^3.5.2

dependencies:
  web_socket: ^0.1.6
  dio: ^5.8.0+1
  clock: ^1.1.1
  collection: ^1.18.0
  stack_trace: ^1.10.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
